# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 465)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 40, 111, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_extract_feature = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_extract_feature.setObjectName("btn_extract_feature")
        self.verticalLayout.addWidget(self.btn_extract_feature)
        self.btn_show_feature = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_show_feature.setObjectName("btn_show_feature")
        self.verticalLayout.addWidget(self.btn_show_feature)
        self.btn_train_model = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_train_model.setObjectName("btn_train_model")
        self.verticalLayout.addWidget(self.btn_train_model)
        self.btn_pre_single = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_pre_single.setObjectName("btn_pre_single")
        self.verticalLayout.addWidget(self.btn_pre_single)
        self.qlabel_background = QtWidgets.QLabel(self.centralwidget)
        self.qlabel_background.setGeometry(QtCore.QRect(-20, -40, 881, 521))
        self.qlabel_background.setObjectName("qlabel_background")
        self.qlabel_picture = QtWidgets.QLabel(self.centralwidget)
        self.qlabel_picture.setGeometry(QtCore.QRect(250, 60, 231, 321))
        self.qlabel_picture.setObjectName("qlabel_picture")
        self.qTE_show_mess = QtWidgets.QTextEdit(self.centralwidget)
        self.qTE_show_mess.setGeometry(QtCore.QRect(560, 70, 191, 291))
        self.qTE_show_mess.setObjectName("qTE_show_mess")
        self.qlabel_background.raise_()
        self.verticalLayoutWidget.raise_()
        self.qlabel_picture.raise_()
        self.qTE_show_mess.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 28))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.btn_train_model.clicked.connect(MainWindow.train_model)
        self.btn_extract_feature.clicked.connect(MainWindow.extract_feature)
        self.btn_pre_single.clicked.connect(MainWindow.pre_single)
        self.btn_show_feature.clicked.connect(MainWindow.show_feature)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_extract_feature.setText(_translate("MainWindow", "提取特征"))
        self.btn_show_feature.setText(_translate("MainWindow", "展示特征"))
        self.btn_train_model.setText(_translate("MainWindow", "训练模型"))
        self.btn_pre_single.setText(_translate("MainWindow", "预测文件"))
        self.qlabel_background.setText(_translate("MainWindow", "loading..."))
        self.qlabel_picture.setText(_translate("MainWindow", "loading..."))
        self.qTE_show_mess.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">The <span style=\" color:#cc0000;\">message</span> of this system will be shown here!</p></body></html>"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.action.setText(_translate("MainWindow", "退出"))
